name: Build Chromium OS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # https://chromium.googlesource.com/chromiumos/docs/+/main/developer_guide.md#Install-development-tools
      - name: Install depot_tools
        run: |
          cd ~
          sudo apt-get install git curl xz-utils python3-pkg-resources python3-virtualenv python3-oauth2client
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "PATH=~/depot_tools:$PATH" >> $GITHUB_ENV

      # https://chromium.googlesource.com/chromiumos/docs/+/main/developer_guide.md#configure-git
      - name: Setup git
        run: |
          git config --global user.email "jay0lee@gmail.com"
          git config --global user.name "Jay Lee"
        
      # 
      - name: Get the source
        run: |
          cd ~
          umask 022
          mkdir -p ~/chromiumos
          cd ~/chromiumos
          echo $PATH
          repo init -u https://chromium.googlesource.com/chromiumos/manifest
          repo sync -j8
